# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerfilePath: '$(Build.SourcesDirectory)/elasticsearch/Dockerfile'
  tag: '$(Build.BuildId)'
  

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      name: "Azure"
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: build
        Dockerfile: $(dockerfilePath)
        tags: |
          $(tag)
        arguments: ELK_VERSION=$(elkVersion)
- stage: Push
  displayName: Push stage
  jobs:  
  - job: Push
    displayName: Push
    pool:
      name: "Azure"
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '$(registryServiceConn)'
        command: 'push'