# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- kibana

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerfilePath: '$(Build.SourcesDirectory)/kibana/Dockerfile'
  imageName: 'greggmca/kibana'
  tag: '$(Build.BuildId)'
  

stages:
- stage: "BuildAndPush"
  displayName: "Build and push $(imageName):$(tag) to Private Registry"
  jobs:  
  - job: "BuildAndPush"
    displayName: "Build and Push for Anthony and Diego"
    pool:
      name: "agents-azure"
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'virginmoneyregistry'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '$(dockerfilePath)'
