# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- logstash

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerfilePath: '$(Build.SourcesDirectory)/logstash/Dockerfile'
  imageName: 'greggmca/logstash'
  tag: '$(Build.BuildId)'
  

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      name: "agents-azure"
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'virginmoneyregistry'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '$(dockerfilePath)'
